# Generated by Django 5.1.4 on 2025-01-21 02:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_cart_product_alter_cart_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Address',
        ),
    ]
