# Generated by Django 5.1.4 on 2025-01-21 05:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_delete_address'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
